spring:
  profiles:
    active: @LocalProfile@

app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/blogtest
    username: postgres
    password: postgres
    pool-size: 30
    sql-script-encoding: UTF-8
    continue-on-error: true
    jndi-name: java:/PostgresDS
