package com.mmanchola.blog.model;

public enum TableFields {
  PERSON_ID,
  PERSON_FIRST_NAME,
  PERSON_LAST_NAME,
  PERSON_GENDER,
  PERSON_AGE,
  PERSON_EMAIL,
  PERSON_PASSWORD,
  PERSON_REGISTERED_AT,
  PERSON_LAST_LOGIN,
  POST_ID,
  POST_PERSON_ID,
  POST_PARENT_ID,
  POST_PARENT_PATH,
  POST_TITLE,
  POST_METATITLE,
  POST_SLUG,
  POST_STATUS,
  POST_PUBLISHED_AT,
  POST_UPDATED_AT,
  POST_CONTENT,
  ROLE_ID,
  ROLE_NAME,
  ROLE_DESCRIPTION,
  TAG_ID,
  TAG_TITLE,
  TAG_METATITLE,
  TAG_SLUG,
  TAG_CONTENT,
  CATEGORY_ID,
  CATEGORY_PARENT_ID,
  CATEGORY_TITLE,
  CATEGORY_METATITLE,
  CATEGORY_SLUG,
  CATEGORY_CONTENT;

  @Override
  public String toString() {
    return super
        .toString()
        .toLowerCase()
        .replace('_', ' ');
  }
}
